### ISSUE TITLE
this is a fucking clone of bastion bot

### ISSUE THREAD

**Issue by oooboooy** [imaginebeingme/Knave#4]
STILL A FUCKING CLONE OF BASTION BOT
YOU FUCKING CHEAT
YOU CAN'T HIDE THAT IT'S A CLONE BY CHANGING THE BOT NAME FROM COCK BOT
I WILL REPORT YOU TO THE ORIGINAL DEV AGAIN

YOU CAN'T HIDE THE FACT THAT YOU R A CHEAT BY CLOSING MY GENUINE ISSUE

**Comment by imaginebeingme** [comment]
Cuck bot * also going back to that noob
